apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-unknown-domain
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: app.unknown-domain.org
spec:
  parentRefs:
  - name: default-gateway
    namespace: envoy-gateway-system
  hostnames:
  - app.unknown-domain.org
  rules:
  - backendRefs:
    - name: whoami
      port: 80
