apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: test-endpoint
  namespace: default
spec:
  endpoints:
  - dnsName: endpoint-app.example.com
    recordTTL: 300
    recordType: A
    targets:
    - 10.0.0.1
